const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_FORECASTLIST: 'FETCH_FORECASTLIST',
    FETCH_FORECAST: 'FETCH_FORECAST',
    SET_MOVIE: 'SET_FORECAST'
}

export default Constants;
